Remove version check for diff color because it was causing an error on titan

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -27,12 +27,13 @@ alias svn="python $HOME/misc/svn-color/svn-color.py"
 alias svnlog="svn log -l 5 -v"
 
 ## Set diff colors (default palette is --palette="rs=0:hd=1:ad=32:de=31:ln=36") (only available in diffutils version >= 3.4)
-diffver=$(diff -v | sed -n '1 s/^.*\s\([0-9.]*\)$/\1/p')
-vertest=$(vercomp $diffver 3.4)
-vertestresult=$?
-if [ $vertestresult -lt 2 ]; then
+## Error when trying to check version on titan: "cannot execute binary file"
+#diffver=$(diff -v | sed -n '1 s/^.*\s\([0-9.]*\)$/\1/p')
+#vertest=$(vercomp $diffver 3.4)
+#vertestresult=$?
+#if [ $vertestresult -lt 2 ]; then
     alias diff="diff --color=auto"
-fi
+#fi
 
 ## Queue management (LSF for Summit, SLURM for NERSC machines, MOAB for other OLCF machines)
 if [ $HOST_SHORT == "summit" -o $HOST_SHORT == "summitdev" ]; then
@@ -53,14 +54,6 @@ if [ $HOST_SHORT == "summit" -o $HOST_SHORT == "summitdev" ]; then
     alias bsubi="bsub -P $PROJID -nnodes 1 -W 00:30 -Is $SHELL"
     alias bsubi_2nodes="bsub -P $PROJID -nnodes 2 -W 00:30 -Is $SHELL"
     alias bsubi_8nodes="bsub -P $PROJID -nnodes 8 -W 00:30 -Is $SHELL"
-
-    ## Count available nodes
-    if [ $HOST_SHORT == "summitdev" ]; then
-        ## This removes known bad nodes from the list
-        alias bnodes_ok="bhosts | grep 'ok' | grep -v -e 'r0c0n07' -e 'r0c0n10' -e 'r0c0n12' -e 'r0c1n10' -e 'r0c1n13' -e 'r0c1n14' -e 'r0c1n15' -e 'r0c1n16' -e 'r0c2n09' -e 'r0c2n16' | wc -l"
-    else
-        alias bnodes_ok="bhosts | grep '^[abc].*\<ok\>' | wc -l"
-    fi
 
     ## Submit directory of job
     alias bjobsls="bjobs -o 'sub_cwd'"
